services:
  - type: web
    name: tecno-cf
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python-3.10.13
    rootDir: webapp
    plan: free
